require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - app/controllers/graphql_controller.rb
    - bin/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 120
  Exclude:
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*

Style/Documentation:
  Enabled: false
