version: '3'

services:
  backend: &backend_base
    build: ./backend
    command:
      [ "sh", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    env_file:
      - .env
      - .env.local
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/local/src/myapp
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

  sidekiq:
    <<: *backend_base
    ports: []
    command:
      [ "bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml" ]

  redis:
    image: redis

  frontend:
    build: ./frontend
    command:
      [ "sh", "-c", "yarn dev" ]
    env_file:
      - .env
      - .env.local
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/usr/local/src/frontend
      - frontend-node_modules:/usr/local/src/frontend/node_modules
    tty: true

volumes:
  bundle:
  frontend-node_modules:
